edition = "2021"

# Style

group_imports = "StdExternalCrate"
imports_granularity = "Module"

reoder_impl_items = true

force_explicit_abi = false
struct_field_align_threshold = 8

# Characters

hex_literal_case = "Upper"

trailing_semicolon = false
match_block_trailing_comma = true
match_arm_blocks = false

hard_tabs = true
newline_style = "Unix"

# Lines

format_string = true
merge_derives = false # might change later
condense_wildcard_suffixes = true

use_field_init_shorthand = true
use_try_shorthand = true

where_single_line = true
fn_single_line = true

# Comments

wrap_comments = true
format_code_in_doc_comments = true

